2024-Winter-BootCamp-TeamF/Backend

.github/ISSUE_TEMPLATE/feature.md
config/settings.py
config/urls.py
poetry.lock
pyproject.toml
swagger/file_upload_docs.py
swagger/urls.py
temp/pdf/views.py

feat : swagger

---

config/settings.py
config/urls.py
poetry.lock
pyproject.toml
temp/openaiService.py
temp/pinecone/service.py
temp/pinecone/urls.py
temp/pinecone/views.py

feat) pinecone 데이터 입력

---

config/settings.py
config/urls.py
swagger/file_upload_docs.py
user/serializers.py

[feat/#34] user수정

---

Dockerfile
config/settings.py
docker-compose.yml
poetry.lock
pyproject.toml
temp/pdf/urls.py
temp/pdf/utils.py
temp/pdf/views.py

summary 텍스트 pdf로 변환 후 저장
- 한국어 처리: 나눔고딕 폰트 다운 후 도커 설정
- mysql에 저장된 summary 텍스트를 redis_key로 조회해서 pdf 변환

[feat/#42] summary 텍스트 pdf 저장

---

Dockerfile
config/settings.py
config/urls.py
docker-compose.yml
poetry.lock
prometheus.yml
pyproject.toml

[feat/#47] 프로메테우스 + 그라파나

---

config/settings.py
docker-compose.yml
poetry.lock
pyproject.toml

CORS 에러 설정
- 프론트 3000 포트 허용
- 그라파나 3000 -> 4000으로 변경

[feat/#50] CORS 에러 설정

---

alert-rules.yml
alertmanager.yml
docker-compose.yml
prometheus.yml

cAdvisor 연결, 슬랙 모니터링 알람 연동
- cAdvisor
- 슬랙 알람

[Setting/#52] cAdvisor, 슬랙 연동

---

poetry.lock
temp/langchain/tasks.py
temp/langchain/urls.py
temp/langchain/views.py

[refactor/#55] pinecone삭제 및 poetry수정

---

temp/pdf/utils.py
temp/pdf/views.py
temp/text/tasks.py

redis와 pinecone에 저장할 때 file_name으로 파일 이름이 함께 저장되도록 수정

[Bug/#64] 파일 이름 저장 수정

---

temp/langchain/services.py
temp/langchain/tasks.py
temp/langchain/views.py

*한 줄 설명*
top_k값을 사용자에게 받아오게 수정
-
*실행 결과 스크린샷*

[refactor/#69]  top_k값을 사용자에게 받아오게 수정

---

temp/langchain/urls.py
temp/langchain/views.py
temp/question/urls.py
temp/question/views.py

refactor : 삭제기능구현

---

temp/morequestion/serializer.py
temp/morequestion/urls.py
temp/morequestion/views.py
temp/question/serializer.py
temp/question/urls.py
temp/question/views.py

*한 줄 설명*
문제 조회 구현
-
*실행 결과 스크린샷*

[feat/#81] 문제 조회 구현

---

temp/morequestion/urls.py
temp/question/urls.py

*한 줄 설명*
잘못된 url 수정
-
*실행 결과 스크린샷*

[refactor/#81] url 수정

---

Dockerfile
Jenkinsfile

*한 줄 설명*
파이프라인 구현
-
*실행 결과 스크린샷*

[Feat/#91] 파이프라인 구현

---

temp/morequestion/urls.py
temp/morequestion/views.py
temp/question/urls.py
temp/question/views.py

*한 줄 설명*
헷갈린 문제 출력
-
*실행 결과 스크린샷*

[feat/#96] 헷갈린 문제 출력

---

temp/langchain/views.py
temp/morequestion/views.py
temp/pinecone/views.py
temp/question/views.py
temp/text/views.py
temp/views.py

추가연습문제 오류 수정
- namespace 변경 (user_id)
- 참조 metadata 이름 변경
- 스웨거 설명 한국어로 변경

[Bug/#101] 추가연습문제 오류 수정

---

temp/openaiService.py

[refactor/#106] summary 글자수 제한 수정

---

temp/langchain/urls.py
temp/morequestion/urls.py
temp/pdf/urls.py
temp/pinecone/urls.py
temp/question/urls.py
user/urls.py

[refactor/#108] /빼기

---

temp/morequestion/serializer.py
temp/question/serializer.py

[refactor/#109]  문제 조회 반환값 추가

---

temp/langchain/services.py
temp/langchain/tasks.py
temp/langchain/utils.py
temp/langchain/views.py

사용자 인풋값에서 top_k 10으로 고정
- top_k 10으로 수정
- summary 텍스트 수정

[Refactor/#112] top_k 고정
